Development
AndyTheNerd/Storehaus pull request #35
Opened 2020-09-23 01:44 UTC by AndyTheNerd

2020-09-23 09:43 UTC, Patross requested changes
Refer to comments in anime.js

2020-09-23 09:43 UTC, Patross commented on commands/anime.js
> +            fetch(`https://animechanapi.xyz/api/quotes?anime=${option}`)
For certain animes there either seems to be no data or different response format since I'm getting this error, needs to get some error handling done: UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'quote' of undefined

data used: re zero && re:zero

2020-09-23 12:20 UTC, AndyTheNerd commented on commands/anime.js
> +            fetch(`https://animechanapi.xyz/api/quotes?anime=${option}`)
Heard

2020-09-24 03:10 UTC, AndyTheNerd commented
Pat is a legend thank ye

2020-09-24 03:11 UTC, merged